
CREATE TABLE IF NOT EXISTS Groups (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    color TEXT NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Task (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    groupId INTEGER NULL,
    name TEXT NOT NULL,
    system TEXT NOT NULL,
    systemId INTEGER,
    recurrence TEXT NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    inArow INTEGER DEFAULT 0,
    FOREIGN KEY (groupId) REFERENCES Groups(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS SmartTimer (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nbRep INTEGER NOT NULL,
    nbSeries INTEGER NOT NULL,
    currentRep INTEGER NOT NULL,
    currentSeries INTEGER NOT NULL,
    timeRecup INTEGER NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Timer (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nbHours INT NOT NULL,
    nbMinutes INT NOT NULL,
    nbSeconds INT NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);